{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   AssertionError: Assertion failed with keyword results\n   assert False\n    +  where False = <bound method GoogleResultPage.verify_keyword_result_2 of <Pages.Googleresultpage.GoogleResultPage object at 0x107416650>>('myntra')\n    +    where <bound method GoogleResultPage.verify_keyword_result_2 of <Pages.Googleresultpage.GoogleResultPage object at 0x107416650>> = <Pages.Googleresultpage.GoogleResultPage object at 0x107416650>.verify_keyword_result_2\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=61183): Max retries exceeded with url: /session/1c7352a4ee0d2cbcc359757de4c7809c/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107415c90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_search_feature", "rerun": "0"}}, "suite_name": "Tests/Web/step_defs/test_demo.py"}}}, "date": "August 26, 2022", "start_time": 1661456971.028219, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}